/*
 * generated by Xtext 2.14.0
 */
package de.dc.fx.ui.model.ui;

import com.google.inject.Injector;
import de.dc.fx.ui.model.fxdsl.ui.internal.FxdslActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FXDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(FxdslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		FxdslActivator activator = FxdslActivator.getInstance();
		return activator != null ? activator.getInjector(FxdslActivator.DE_DC_FX_UI_MODEL_FXDSL) : null;
	}

}
