/*
 * generated by Xtext 2.14.0
 */
package de.dc.fx.ui.model


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class FXDslRuntimeModule extends AbstractFXDslRuntimeModule {
}
