/*
 * generated by Xtext 2.14.0
 */
package de.dc.fx.ui.model


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FXDslStandaloneSetup extends FXDslStandaloneSetupGenerated {

	def static void doSetup() {
		new FXDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
