/*
 * generated by Xtext 2.14.0
 */
package de.dc.fx.ui.model.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class FXDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class FXTableViewElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.fx.ui.model.FXDsl.FXTableView");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFXTableViewAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cHasFilterAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cHasFilterHasFilterKeyword_1_0 = (Keyword)cHasFilterAssignment_1.eContents().get(0);
		private final Assignment cHasSorterAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cHasSorterHasSorterKeyword_2_0 = (Keyword)cHasSorterAssignment_2.eContents().get(0);
		private final Keyword cFXTableViewKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameEStringParserRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPackagePathKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPackagePathAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cPackagePathEStringParserRuleCall_6_1_0 = (RuleCall)cPackagePathAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cFxColumnsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cFxColumnsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cFxColumnsFXColumnParserRuleCall_7_2_0 = (RuleCall)cFxColumnsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cFxColumnsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cFxColumnsFXColumnParserRuleCall_7_3_1_0 = (RuleCall)cFxColumnsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cFxEntityKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cFxEntityAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cFxEntityFXModelParserRuleCall_8_1_0 = (RuleCall)cFxEntityAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//FXTableView:
		//	{FXTableView} hasFilter?='hasFilter'?
		//	hasSorter?='hasSorter'?
		//	'FXTableView'
		//	name=EString
		//	'{' ('packagePath' packagePath=EString)? ('fxColumns' '{' fxColumns+=FXColumn ("," fxColumns+=FXColumn)* '}')?
		//	('fxEntity' fxEntity=FXModel)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{FXTableView} hasFilter?='hasFilter'? hasSorter?='hasSorter'? 'FXTableView' name=EString '{' ('packagePath'
		//packagePath=EString)? ('fxColumns' '{' fxColumns+=FXColumn ("," fxColumns+=FXColumn)* '}')? ('fxEntity'
		//fxEntity=FXModel)? '}'
		public Group getGroup() { return cGroup; }
		
		//{FXTableView}
		public Action getFXTableViewAction_0() { return cFXTableViewAction_0; }
		
		//hasFilter?='hasFilter'?
		public Assignment getHasFilterAssignment_1() { return cHasFilterAssignment_1; }
		
		//'hasFilter'
		public Keyword getHasFilterHasFilterKeyword_1_0() { return cHasFilterHasFilterKeyword_1_0; }
		
		//hasSorter?='hasSorter'?
		public Assignment getHasSorterAssignment_2() { return cHasSorterAssignment_2; }
		
		//'hasSorter'
		public Keyword getHasSorterHasSorterKeyword_2_0() { return cHasSorterHasSorterKeyword_2_0; }
		
		//'FXTableView'
		public Keyword getFXTableViewKeyword_3() { return cFXTableViewKeyword_3; }
		
		//name=EString
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_4_0() { return cNameEStringParserRuleCall_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//('packagePath' packagePath=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'packagePath'
		public Keyword getPackagePathKeyword_6_0() { return cPackagePathKeyword_6_0; }
		
		//packagePath=EString
		public Assignment getPackagePathAssignment_6_1() { return cPackagePathAssignment_6_1; }
		
		//EString
		public RuleCall getPackagePathEStringParserRuleCall_6_1_0() { return cPackagePathEStringParserRuleCall_6_1_0; }
		
		//('fxColumns' '{' fxColumns+=FXColumn ("," fxColumns+=FXColumn)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'fxColumns'
		public Keyword getFxColumnsKeyword_7_0() { return cFxColumnsKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//fxColumns+=FXColumn
		public Assignment getFxColumnsAssignment_7_2() { return cFxColumnsAssignment_7_2; }
		
		//FXColumn
		public RuleCall getFxColumnsFXColumnParserRuleCall_7_2_0() { return cFxColumnsFXColumnParserRuleCall_7_2_0; }
		
		//("," fxColumns+=FXColumn)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//fxColumns+=FXColumn
		public Assignment getFxColumnsAssignment_7_3_1() { return cFxColumnsAssignment_7_3_1; }
		
		//FXColumn
		public RuleCall getFxColumnsFXColumnParserRuleCall_7_3_1_0() { return cFxColumnsFXColumnParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//('fxEntity' fxEntity=FXModel)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'fxEntity'
		public Keyword getFxEntityKeyword_8_0() { return cFxEntityKeyword_8_0; }
		
		//fxEntity=FXModel
		public Assignment getFxEntityAssignment_8_1() { return cFxEntityAssignment_8_1; }
		
		//FXModel
		public RuleCall getFxEntityFXModelParserRuleCall_8_1_0() { return cFxEntityFXModelParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.fx.ui.model.FXDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class FXColumnElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.fx.ui.model.FXDsl.FXColumn");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFXColumnAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cEditableAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cEditableEditableKeyword_1_0 = (Keyword)cEditableAssignment_1.eContents().get(0);
		private final Assignment cUseCustomCellFactoryAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cUseCustomCellFactoryUseCustomCellFactoryKeyword_2_0 = (Keyword)cUseCustomCellFactoryAssignment_2.eContents().get(0);
		private final Keyword cFXColumnKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameEStringParserRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cWidthKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cWidthAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cWidthEDoubleParserRuleCall_6_1_0 = (RuleCall)cWidthAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cAlignmentKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cAlignmentAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cAlignmentPosEnumRuleCall_7_1_0 = (RuleCall)cAlignmentAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cAssociatedFXPropertyKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cAssociatedFXPropertyAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final CrossReference cAssociatedFXPropertyFXPropertyCrossReference_8_1_0 = (CrossReference)cAssociatedFXPropertyAssignment_8_1.eContents().get(0);
		private final RuleCall cAssociatedFXPropertyFXPropertyEStringParserRuleCall_8_1_0_1 = (RuleCall)cAssociatedFXPropertyFXPropertyCrossReference_8_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//FXColumn:
		//	{FXColumn} editable?='editable'?
		//	useCustomCellFactory?='useCustomCellFactory'?
		//	'FXColumn'
		//	name=EString
		//	'{' ('width' width=EDouble)? ('alignment' alignment=Pos)? ('associatedFXProperty'
		//	associatedFXProperty=[FXProperty|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{FXColumn} editable?='editable'? useCustomCellFactory?='useCustomCellFactory'? 'FXColumn' name=EString '{' ('width'
		//width=EDouble)? ('alignment' alignment=Pos)? ('associatedFXProperty' associatedFXProperty=[FXProperty|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{FXColumn}
		public Action getFXColumnAction_0() { return cFXColumnAction_0; }
		
		//editable?='editable'?
		public Assignment getEditableAssignment_1() { return cEditableAssignment_1; }
		
		//'editable'
		public Keyword getEditableEditableKeyword_1_0() { return cEditableEditableKeyword_1_0; }
		
		//useCustomCellFactory?='useCustomCellFactory'?
		public Assignment getUseCustomCellFactoryAssignment_2() { return cUseCustomCellFactoryAssignment_2; }
		
		//'useCustomCellFactory'
		public Keyword getUseCustomCellFactoryUseCustomCellFactoryKeyword_2_0() { return cUseCustomCellFactoryUseCustomCellFactoryKeyword_2_0; }
		
		//'FXColumn'
		public Keyword getFXColumnKeyword_3() { return cFXColumnKeyword_3; }
		
		//name=EString
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_4_0() { return cNameEStringParserRuleCall_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//('width' width=EDouble)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'width'
		public Keyword getWidthKeyword_6_0() { return cWidthKeyword_6_0; }
		
		//width=EDouble
		public Assignment getWidthAssignment_6_1() { return cWidthAssignment_6_1; }
		
		//EDouble
		public RuleCall getWidthEDoubleParserRuleCall_6_1_0() { return cWidthEDoubleParserRuleCall_6_1_0; }
		
		//('alignment' alignment=Pos)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'alignment'
		public Keyword getAlignmentKeyword_7_0() { return cAlignmentKeyword_7_0; }
		
		//alignment=Pos
		public Assignment getAlignmentAssignment_7_1() { return cAlignmentAssignment_7_1; }
		
		//Pos
		public RuleCall getAlignmentPosEnumRuleCall_7_1_0() { return cAlignmentPosEnumRuleCall_7_1_0; }
		
		//('associatedFXProperty' associatedFXProperty=[FXProperty|EString])?
		public Group getGroup_8() { return cGroup_8; }
		
		//'associatedFXProperty'
		public Keyword getAssociatedFXPropertyKeyword_8_0() { return cAssociatedFXPropertyKeyword_8_0; }
		
		//associatedFXProperty=[FXProperty|EString]
		public Assignment getAssociatedFXPropertyAssignment_8_1() { return cAssociatedFXPropertyAssignment_8_1; }
		
		//[FXProperty|EString]
		public CrossReference getAssociatedFXPropertyFXPropertyCrossReference_8_1_0() { return cAssociatedFXPropertyFXPropertyCrossReference_8_1_0; }
		
		//EString
		public RuleCall getAssociatedFXPropertyFXPropertyEStringParserRuleCall_8_1_0_1() { return cAssociatedFXPropertyFXPropertyEStringParserRuleCall_8_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class FXModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.fx.ui.model.FXDsl.FXModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFXModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFXModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cFxPropertiesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cFxPropertiesAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cFxPropertiesFXPropertyParserRuleCall_4_2_0 = (RuleCall)cFxPropertiesAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cFxPropertiesAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cFxPropertiesFXPropertyParserRuleCall_4_3_1_0 = (RuleCall)cFxPropertiesAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//FXModel:
		//	{FXModel}
		//	'FXModel'
		//	name=EString
		//	'{' ('fxProperties' '{' fxProperties+=FXProperty ("," fxProperties+=FXProperty)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{FXModel} 'FXModel' name=EString '{' ('fxProperties' '{' fxProperties+=FXProperty ("," fxProperties+=FXProperty)* '}')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{FXModel}
		public Action getFXModelAction_0() { return cFXModelAction_0; }
		
		//'FXModel'
		public Keyword getFXModelKeyword_1() { return cFXModelKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('fxProperties' '{' fxProperties+=FXProperty ("," fxProperties+=FXProperty)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'fxProperties'
		public Keyword getFxPropertiesKeyword_4_0() { return cFxPropertiesKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//fxProperties+=FXProperty
		public Assignment getFxPropertiesAssignment_4_2() { return cFxPropertiesAssignment_4_2; }
		
		//FXProperty
		public RuleCall getFxPropertiesFXPropertyParserRuleCall_4_2_0() { return cFxPropertiesFXPropertyParserRuleCall_4_2_0; }
		
		//("," fxProperties+=FXProperty)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//fxProperties+=FXProperty
		public Assignment getFxPropertiesAssignment_4_3_1() { return cFxPropertiesAssignment_4_3_1; }
		
		//FXProperty
		public RuleCall getFxPropertiesFXPropertyParserRuleCall_4_3_1_0() { return cFxPropertiesFXPropertyParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.fx.ui.model.FXDsl.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class FXPropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.fx.ui.model.FXDsl.FXProperty");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFXPropertyAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFXPropertyKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_4_1_0 = (RuleCall)cTypeAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//FXProperty:
		//	{FXProperty}
		//	'FXProperty'
		//	name=EString
		//	'{' ('type' type=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{FXProperty} 'FXProperty' name=EString '{' ('type' type=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//{FXProperty}
		public Action getFXPropertyAction_0() { return cFXPropertyAction_0; }
		
		//'FXProperty'
		public Keyword getFXPropertyKeyword_1() { return cFXPropertyKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('type' type=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'type'
		public Keyword getTypeKeyword_4_0() { return cTypeKeyword_4_0; }
		
		//type=EString
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }
		
		//EString
		public RuleCall getTypeEStringParserRuleCall_4_1_0() { return cTypeEStringParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.fx.ui.model.FXDsl.EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EDouble ecore::EDouble:
		//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E' | 'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E' | 'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'E' | 'e'
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	
	public class PosElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "de.dc.fx.ui.model.FXDsl.Pos");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cTOP_LEFTEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cTOP_LEFTTOP_LEFTKeyword_0_0 = (Keyword)cTOP_LEFTEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cTOP_CENTEREnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cTOP_CENTERTOP_CENTERKeyword_1_0 = (Keyword)cTOP_CENTEREnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cTOP_RIGHTEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cTOP_RIGHTTOP_RIGHTKeyword_2_0 = (Keyword)cTOP_RIGHTEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cCENTER_LEFTEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cCENTER_LEFTCENTER_LEFTKeyword_3_0 = (Keyword)cCENTER_LEFTEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cCENTEREnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cCENTERCENTERKeyword_4_0 = (Keyword)cCENTEREnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cCENTER_RIGHTEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cCENTER_RIGHTCENTER_RIGHTKeyword_5_0 = (Keyword)cCENTER_RIGHTEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cBOTTOM_LEFTEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cBOTTOM_LEFTBOTTOM_LEFTKeyword_6_0 = (Keyword)cBOTTOM_LEFTEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cBOTTOM_CENTEREnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cBOTTOM_CENTERBOTTOM_CENTERKeyword_7_0 = (Keyword)cBOTTOM_CENTEREnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cBOTTOM_RIGHTEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cBOTTOM_RIGHTBOTTOM_RIGHTKeyword_8_0 = (Keyword)cBOTTOM_RIGHTEnumLiteralDeclaration_8.eContents().get(0);
		
		//enum Pos:
		//	TOP_LEFT | TOP_CENTER | TOP_RIGHT | CENTER_LEFT | CENTER | CENTER_RIGHT | BOTTOM_LEFT | BOTTOM_CENTER | BOTTOM_RIGHT;
		public EnumRule getRule() { return rule; }
		
		//TOP_LEFT | TOP_CENTER | TOP_RIGHT | CENTER_LEFT | CENTER | CENTER_RIGHT | BOTTOM_LEFT | BOTTOM_CENTER | BOTTOM_RIGHT
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TOP_LEFT
		public EnumLiteralDeclaration getTOP_LEFTEnumLiteralDeclaration_0() { return cTOP_LEFTEnumLiteralDeclaration_0; }
		
		//'TOP_LEFT'
		public Keyword getTOP_LEFTTOP_LEFTKeyword_0_0() { return cTOP_LEFTTOP_LEFTKeyword_0_0; }
		
		//TOP_CENTER
		public EnumLiteralDeclaration getTOP_CENTEREnumLiteralDeclaration_1() { return cTOP_CENTEREnumLiteralDeclaration_1; }
		
		//'TOP_CENTER'
		public Keyword getTOP_CENTERTOP_CENTERKeyword_1_0() { return cTOP_CENTERTOP_CENTERKeyword_1_0; }
		
		//TOP_RIGHT
		public EnumLiteralDeclaration getTOP_RIGHTEnumLiteralDeclaration_2() { return cTOP_RIGHTEnumLiteralDeclaration_2; }
		
		//'TOP_RIGHT'
		public Keyword getTOP_RIGHTTOP_RIGHTKeyword_2_0() { return cTOP_RIGHTTOP_RIGHTKeyword_2_0; }
		
		//CENTER_LEFT
		public EnumLiteralDeclaration getCENTER_LEFTEnumLiteralDeclaration_3() { return cCENTER_LEFTEnumLiteralDeclaration_3; }
		
		//'CENTER_LEFT'
		public Keyword getCENTER_LEFTCENTER_LEFTKeyword_3_0() { return cCENTER_LEFTCENTER_LEFTKeyword_3_0; }
		
		//CENTER
		public EnumLiteralDeclaration getCENTEREnumLiteralDeclaration_4() { return cCENTEREnumLiteralDeclaration_4; }
		
		//'CENTER'
		public Keyword getCENTERCENTERKeyword_4_0() { return cCENTERCENTERKeyword_4_0; }
		
		//CENTER_RIGHT
		public EnumLiteralDeclaration getCENTER_RIGHTEnumLiteralDeclaration_5() { return cCENTER_RIGHTEnumLiteralDeclaration_5; }
		
		//'CENTER_RIGHT'
		public Keyword getCENTER_RIGHTCENTER_RIGHTKeyword_5_0() { return cCENTER_RIGHTCENTER_RIGHTKeyword_5_0; }
		
		//BOTTOM_LEFT
		public EnumLiteralDeclaration getBOTTOM_LEFTEnumLiteralDeclaration_6() { return cBOTTOM_LEFTEnumLiteralDeclaration_6; }
		
		//'BOTTOM_LEFT'
		public Keyword getBOTTOM_LEFTBOTTOM_LEFTKeyword_6_0() { return cBOTTOM_LEFTBOTTOM_LEFTKeyword_6_0; }
		
		//BOTTOM_CENTER
		public EnumLiteralDeclaration getBOTTOM_CENTEREnumLiteralDeclaration_7() { return cBOTTOM_CENTEREnumLiteralDeclaration_7; }
		
		//'BOTTOM_CENTER'
		public Keyword getBOTTOM_CENTERBOTTOM_CENTERKeyword_7_0() { return cBOTTOM_CENTERBOTTOM_CENTERKeyword_7_0; }
		
		//BOTTOM_RIGHT
		public EnumLiteralDeclaration getBOTTOM_RIGHTEnumLiteralDeclaration_8() { return cBOTTOM_RIGHTEnumLiteralDeclaration_8; }
		
		//'BOTTOM_RIGHT'
		public Keyword getBOTTOM_RIGHTBOTTOM_RIGHTKeyword_8_0() { return cBOTTOM_RIGHTBOTTOM_RIGHTKeyword_8_0; }
	}
	
	private final FXTableViewElements pFXTableView;
	private final EStringElements pEString;
	private final FXColumnElements pFXColumn;
	private final FXModelElements pFXModel;
	private final EBooleanElements pEBoolean;
	private final FXPropertyElements pFXProperty;
	private final EDoubleElements pEDouble;
	private final PosElements ePos;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public FXDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pFXTableView = new FXTableViewElements();
		this.pEString = new EStringElements();
		this.pFXColumn = new FXColumnElements();
		this.pFXModel = new FXModelElements();
		this.pEBoolean = new EBooleanElements();
		this.pFXProperty = new FXPropertyElements();
		this.pEDouble = new EDoubleElements();
		this.ePos = new PosElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.dc.fx.ui.model.FXDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//FXTableView:
	//	{FXTableView} hasFilter?='hasFilter'?
	//	hasSorter?='hasSorter'?
	//	'FXTableView'
	//	name=EString
	//	'{' ('packagePath' packagePath=EString)? ('fxColumns' '{' fxColumns+=FXColumn ("," fxColumns+=FXColumn)* '}')?
	//	('fxEntity' fxEntity=FXModel)?
	//	'}';
	public FXTableViewElements getFXTableViewAccess() {
		return pFXTableView;
	}
	
	public ParserRule getFXTableViewRule() {
		return getFXTableViewAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//FXColumn:
	//	{FXColumn} editable?='editable'?
	//	useCustomCellFactory?='useCustomCellFactory'?
	//	'FXColumn'
	//	name=EString
	//	'{' ('width' width=EDouble)? ('alignment' alignment=Pos)? ('associatedFXProperty'
	//	associatedFXProperty=[FXProperty|EString])?
	//	'}';
	public FXColumnElements getFXColumnAccess() {
		return pFXColumn;
	}
	
	public ParserRule getFXColumnRule() {
		return getFXColumnAccess().getRule();
	}
	
	//FXModel:
	//	{FXModel}
	//	'FXModel'
	//	name=EString
	//	'{' ('fxProperties' '{' fxProperties+=FXProperty ("," fxProperties+=FXProperty)* '}')?
	//	'}';
	public FXModelElements getFXModelAccess() {
		return pFXModel;
	}
	
	public ParserRule getFXModelRule() {
		return getFXModelAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//FXProperty:
	//	{FXProperty}
	//	'FXProperty'
	//	name=EString
	//	'{' ('type' type=EString)?
	//	'}';
	public FXPropertyElements getFXPropertyAccess() {
		return pFXProperty;
	}
	
	public ParserRule getFXPropertyRule() {
		return getFXPropertyAccess().getRule();
	}
	
	//EDouble ecore::EDouble:
	//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
	public EDoubleElements getEDoubleAccess() {
		return pEDouble;
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}
	
	//enum Pos:
	//	TOP_LEFT | TOP_CENTER | TOP_RIGHT | CENTER_LEFT | CENTER | CENTER_RIGHT | BOTTOM_LEFT | BOTTOM_CENTER | BOTTOM_RIGHT;
	public PosElements getPosAccess() {
		return ePos;
	}
	
	public EnumRule getPosRule() {
		return getPosAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
