/**
 * generated by Xtext 2.14.0
 */
package de.dc.fx.ui.model.fxui;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FX Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.dc.fx.ui.model.fxui.FXModel#getName <em>Name</em>}</li>
 *   <li>{@link de.dc.fx.ui.model.fxui.FXModel#getFxProperties <em>Fx Properties</em>}</li>
 * </ul>
 *
 * @see de.dc.fx.ui.model.fxui.FxuiPackage#getFXModel()
 * @model
 * @generated
 */
public interface FXModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.dc.fx.ui.model.fxui.FxuiPackage#getFXModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.dc.fx.ui.model.fxui.FXModel#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Fx Properties</b></em>' containment reference list.
   * The list contents are of type {@link de.dc.fx.ui.model.fxui.FXProperty}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fx Properties</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fx Properties</em>' containment reference list.
   * @see de.dc.fx.ui.model.fxui.FxuiPackage#getFXModel_FxProperties()
   * @model containment="true"
   * @generated
   */
  EList<FXProperty> getFxProperties();

} // FXModel
