/**
 * generated by Xtext 2.14.0
 */
package de.dc.fx.ui.model.fxui;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Pos</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see de.dc.fx.ui.model.fxui.FxuiPackage#getPos()
 * @model
 * @generated
 */
public enum Pos implements Enumerator
{
  /**
   * The '<em><b>TOP LEFT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TOP_LEFT_VALUE
   * @generated
   * @ordered
   */
  TOP_LEFT(0, "TOP_LEFT", "TOP_LEFT"),

  /**
   * The '<em><b>TOP CENTER</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TOP_CENTER_VALUE
   * @generated
   * @ordered
   */
  TOP_CENTER(1, "TOP_CENTER", "TOP_CENTER"),

  /**
   * The '<em><b>TOP RIGHT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TOP_RIGHT_VALUE
   * @generated
   * @ordered
   */
  TOP_RIGHT(2, "TOP_RIGHT", "TOP_RIGHT"),

  /**
   * The '<em><b>CENTER LEFT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CENTER_LEFT_VALUE
   * @generated
   * @ordered
   */
  CENTER_LEFT(3, "CENTER_LEFT", "CENTER_LEFT"),

  /**
   * The '<em><b>CENTER</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CENTER_VALUE
   * @generated
   * @ordered
   */
  CENTER(4, "CENTER", "CENTER"),

  /**
   * The '<em><b>CENTER RIGHT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CENTER_RIGHT_VALUE
   * @generated
   * @ordered
   */
  CENTER_RIGHT(5, "CENTER_RIGHT", "CENTER_RIGHT"),

  /**
   * The '<em><b>BOTTOM LEFT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BOTTOM_LEFT_VALUE
   * @generated
   * @ordered
   */
  BOTTOM_LEFT(6, "BOTTOM_LEFT", "BOTTOM_LEFT"),

  /**
   * The '<em><b>BOTTOM CENTER</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BOTTOM_CENTER_VALUE
   * @generated
   * @ordered
   */
  BOTTOM_CENTER(7, "BOTTOM_CENTER", "BOTTOM_CENTER"),

  /**
   * The '<em><b>BOTTOM RIGHT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BOTTOM_RIGHT_VALUE
   * @generated
   * @ordered
   */
  BOTTOM_RIGHT(8, "BOTTOM_RIGHT", "BOTTOM_RIGHT");

  /**
   * The '<em><b>TOP LEFT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>TOP LEFT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TOP_LEFT
   * @model
   * @generated
   * @ordered
   */
  public static final int TOP_LEFT_VALUE = 0;

  /**
   * The '<em><b>TOP CENTER</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>TOP CENTER</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TOP_CENTER
   * @model
   * @generated
   * @ordered
   */
  public static final int TOP_CENTER_VALUE = 1;

  /**
   * The '<em><b>TOP RIGHT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>TOP RIGHT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TOP_RIGHT
   * @model
   * @generated
   * @ordered
   */
  public static final int TOP_RIGHT_VALUE = 2;

  /**
   * The '<em><b>CENTER LEFT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>CENTER LEFT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CENTER_LEFT
   * @model
   * @generated
   * @ordered
   */
  public static final int CENTER_LEFT_VALUE = 3;

  /**
   * The '<em><b>CENTER</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>CENTER</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CENTER
   * @model
   * @generated
   * @ordered
   */
  public static final int CENTER_VALUE = 4;

  /**
   * The '<em><b>CENTER RIGHT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>CENTER RIGHT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CENTER_RIGHT
   * @model
   * @generated
   * @ordered
   */
  public static final int CENTER_RIGHT_VALUE = 5;

  /**
   * The '<em><b>BOTTOM LEFT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>BOTTOM LEFT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #BOTTOM_LEFT
   * @model
   * @generated
   * @ordered
   */
  public static final int BOTTOM_LEFT_VALUE = 6;

  /**
   * The '<em><b>BOTTOM CENTER</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>BOTTOM CENTER</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #BOTTOM_CENTER
   * @model
   * @generated
   * @ordered
   */
  public static final int BOTTOM_CENTER_VALUE = 7;

  /**
   * The '<em><b>BOTTOM RIGHT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>BOTTOM RIGHT</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #BOTTOM_RIGHT
   * @model
   * @generated
   * @ordered
   */
  public static final int BOTTOM_RIGHT_VALUE = 8;

  /**
   * An array of all the '<em><b>Pos</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Pos[] VALUES_ARRAY =
    new Pos[]
    {
      TOP_LEFT,
      TOP_CENTER,
      TOP_RIGHT,
      CENTER_LEFT,
      CENTER,
      CENTER_RIGHT,
      BOTTOM_LEFT,
      BOTTOM_CENTER,
      BOTTOM_RIGHT,
    };

  /**
   * A public read-only list of all the '<em><b>Pos</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Pos> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Pos</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Pos get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Pos result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Pos</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Pos getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Pos result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Pos</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Pos get(int value)
  {
    switch (value)
    {
      case TOP_LEFT_VALUE: return TOP_LEFT;
      case TOP_CENTER_VALUE: return TOP_CENTER;
      case TOP_RIGHT_VALUE: return TOP_RIGHT;
      case CENTER_LEFT_VALUE: return CENTER_LEFT;
      case CENTER_VALUE: return CENTER;
      case CENTER_RIGHT_VALUE: return CENTER_RIGHT;
      case BOTTOM_LEFT_VALUE: return BOTTOM_LEFT;
      case BOTTOM_CENTER_VALUE: return BOTTOM_CENTER;
      case BOTTOM_RIGHT_VALUE: return BOTTOM_RIGHT;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Pos(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Pos
