/*
 * generated by Xtext 2.14.0
 */
package de.dc.fx.ui.model.parser.antlr;

import com.google.inject.Inject;
import de.dc.fx.ui.model.parser.antlr.internal.InternalFXDslParser;
import de.dc.fx.ui.model.services.FXDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class FXDslParser extends AbstractAntlrParser {

	@Inject
	private FXDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFXDslParser createParser(XtextTokenStream stream) {
		return new InternalFXDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "FXTableView";
	}

	public FXDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FXDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
