/*
 * generated by Xtext 2.14.0
 */
package de.dc.fx.ui.model.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFXDslScopeProvider extends DelegatingScopeProvider {
}
