/*
 * generated by Xtext 2.14.0
 */
package de.dc.fx.ui.model.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class FXDslUiModule extends AbstractFXDslUiModule {
}
